#pragma config(Sensor, S1,     TDriver,        sensorEV3_Touch)
#pragma config(Sensor, S2,     GyroDriver,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     ColorDriver,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          ArmDriver,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          WheelLDriver,  tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          WheelRDriver,  tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Variables//////////////////

TLegoColors colorcontri = colorBlue;
TLegoColors colormio = colorRed;

//funcion inicio//////////////////////

void inicio(){
	int var = 1;
	while (var == 1){ //while para que no deje de funcionar el robot.
		displayBigTextLine(4, "Buscando Linea...");
		sleep(20); // Se espera 20 ms para hacer 50 lecturas por segundo

		/*Insertamos unas condicionales el cual es 1 si encuentra el color negro
		y 6 si el color blanco*/
		if (getColorName(ColorDriver) == colorBlack){

			//los motores van de 0 a 100,  0 es cuando esta detenido
			motor [motorB] = 0; //define la velocidad del motor en el puerto B
			motor [motorC] = 0; //define la velocidad del motor en el puerto C
			wait1Msec (20);

			int var2 = 1;

			while(var2 == 1){
				displayBigTextLine(4, "Buscando punto...");
			/*Se utiliza while para poder dirigir el Mindstorm
			por la linea hasta posicicionarlo en el punto verde*/
			/*Se crea condicionales segun los colores negro, blanco o verde,
			este girara a la izquierda o derecha o se detendrá*/
				if (getColorName(ColorDriver) == colorBlack){
					motor [motorB] = 15;
					motor [motorC] = -5;
				}
				else if (getColorName(ColorDriver) == colorWhite){
					motor [motorB] = -5;
					motor [motorC] = 15;
				}
				else if (getColorName(ColorDriver) == colorGreen){
					motor [motorB] = 0;
					motor [motorC] = 0;
					var = 0;
					var2 = 0;
				}
			}
		}
		else if(getColorName(ColorDriver) == colorWhite){
			motor [motorB] = 20; //define la velocidad del motor en el puerto B
			motor [motorC] = 20; //define la velocidad del motor en el puerto C
		}
	}
}
void pos(){
	int var3 = 1;
	while(var3 == 1){
		displayBigTextLine(4, "Buscando posicion...");

		motor [motorB] = 10;
		motor [motorC] = -10;
		if (getColorName(ColorDriver) != colorGreen){

			motor [motorB] = 10;
			motor [motorC] = -10;
		}
		else if (getColorName(ColorDriver) == colorGreen){/*posicionar robot en base a los cuadros*/
			motor [motorB] = 0;
			motor [motorC] = 0;
		}
	}
}
//task main es donde va el desarrollo del codigo si queremos poner funciones se escriben antes//
task main(){
	displayBigTextLine(4, "Contrincante");
	displayBigTextLine(5, "Azul");
	sleep(1000);
	eraseDisplay();
	displayBigTextLine(4, "Color Robot");
	displayBigTextLine(5, "Rojo");
	eraseDisplay();
	sleep(1000);
	//Despues llamo mi funcion de inicio para encontrar el punto inicial
	inicio();
	sleep(20);
	//dirigo mi robot al primer cuadro
	pos();
}
